# Task 2 Encoding and Classifier

## Problem 
<br>
Encoding the following files in a quantum circuit mock_train_set.csv and mock_test_set.csv in at least two different ways (these could be basis, angle, amplitude, kernel or random encoding
<br>
<br>
● Design a variational quantum circuit for each of the encodings, uses the column 4 as the target, this is a binary class 0 and 1.<br>
● You must use the data from column0 to column3 for your proposed classifier.<br>
● Consider the ansatz you are going to design as a layer and find out how many layers are
necessary to reach the best performance. <br>

### Analyze and discuss the results

Feel free to use existing frameworks (e.g. PennyLane, Qiskit) for creating and training the circuits.<br><br>
This PennyLane demo can be useful: Training a quantum circuit with Pytorch,<br>
This Quantum Tensorflow tutorial can be useful: Training a quantum circuit with Tensorflow.<br>
For the variational circuit, you can try any circuit you want. You can start from one with a layer of RX, RZ and CNOTs.<br>
<br>
## References
* https://pennylane.ai/qml/demos/tutorial_state_preparation.html
* https://www.tensorflow.org/quantum/tutorials/mnist

<br>

## Clasification Using Amplitude Encoding on 2 Qubits

In [58]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from ipywidgets import widgets
from IPython.display import display, HTML

In [59]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import NesterovMomentumOptimizer

import sys
from math import sqrt, pi

import pandas as pd
import scipy
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
# supress a warning that is not useful here
pd.options.mode.chained_assignment = None


In [60]:
# sklearn StandardScaler
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

path_train = '/_jupyter/QC/QOSF-challenge-md-2022/task-02/mock_train_set.csv'
path_test = '/_jupyter/QC/QOSF-challenge-md-2022/task-02/mock_test_set.csv'

df = pd.read_csv(path_train)
df_c = df.copy(deep=True)
df['1'] = np.log10(df_c['1'])
df['2'] = np.log10(df_c['2'])

f = lambda x: -1.0 if x==0 else 1.0
df['4'] = df_c['4'].map(f)

# npdf = df2.to_numpy()
npdf = df.to_numpy()
data = np.array(npdf)

print("Train data standardised:\n", data)

X = data[:, 0:4]
Y = data[:, -1]

# scale the data using sklearn StandardScaler
# std_slc = StandardScaler(with_mean=False)
std_slc = StandardScaler(with_mean=True)
std_slc.fit(X)
X_std = std_slc.transform(X)

# normalize data using sklearn StandardScaler
normalizer = Normalizer().fit(X_std)  # fit does nothing.
X_norm = normalizer.transform(X_std)

# features will be the angles vector
# features = np.array(X_norm, requires_grad=False)
features = np.array(X_std, requires_grad=False)
# features = np.array(X, requires_grad=False)
print("Train data normalized:\n", features)




Train data standardised:
 [[ 2.78926e+03  3.00000e+00  1.00000e+00  2.00000e+01 -1.00000e+00]
 [ 4.04001e+03  6.00000e+00  0.00000e+00  1.00000e+00  1.00000e+00]
 [ 2.93120e+03  4.00000e+00  4.00000e+00  4.00000e+01  1.00000e+00]
 ...
 [ 4.18281e+03  0.00000e+00  0.00000e+00  6.50000e+01 -1.00000e+00]
 [ 3.11375e+03  4.00000e+00  2.00000e+00  1.00000e+00  1.00000e+00]
 [ 4.56757e+03  4.00000e+00  5.00000e+00  9.00000e+01  1.00000e+00]]


StandardScaler()

Train data normalized:
 [[ 0.11203099 -0.04899659 -0.85833249 -0.95544758]
 [ 0.99674452  1.21091584 -1.35930477 -1.64780089]
 [ 0.21243174  0.37097422  0.64458432 -0.22665461]
 ...
 [ 1.09775359 -1.30890903 -1.35930477  0.68433659]
 [ 0.34155783  0.37097422 -0.35736022 -1.64780089]
 [ 1.3699122   0.37097422  1.1455566   1.5953278 ]]


Circuit coding for angle encoding follows pennylane technique, whch is also following the scheme in in Schuld and Petruccione (2018).<br>
""We had to also decompose controlled Y-axis rotations into more basic circuits following Nielsen and Chuang (2010).""<br>

* https://link.springer.com/book/10.1007/978-3-319-96424-9
* 

In [61]:
num_qubits = 4
num_layers = 2

dev = qml.device("default.qubit", wires=num_qubits)

### test angle encoding

In [62]:


# circuit that gets trained and optimized
@qml.qnode(dev)
def circuit(weights, data):

    # QAOAEmbedding can take care of both features and weights
    # we dont need extra layers
    qml.QAOAEmbedding(features=data, weights=weights, wires=range(num_qubits))

    return qml.expval(qml.PauliZ(0))

draw_flag = 0
def variational_classifier(weights, bias, data):
    
    return circuit(weights, data) + bias

# ###############################################################################
# standard square loss
def square_loss(labels, predictions):
    
    loss = 0
    for l, p in zip(labels, predictions):
        loss = loss + (l - p) ** 2

    loss = loss / len(labels)
    return loss

# ###############################################################################
# goal: maximize accuracy
def accuracy(labels, predictions):

    loss = 0
    for l, p in zip(labels, predictions):
        if abs(l - p) < 1e-5:
            loss = loss + 1
    loss = loss / len(labels)

    return loss


def cost(weights, bias, features, labels):
    
    predictions = [variational_classifier(weights, bias, f) for f in features]
    return square_loss(labels, predictions)


In [65]:
# ####################################################################
# split train data set in train and evaluation

np.random.seed(0)
num_data = len(Y)

num_train = int(0.75 * num_data)
index = np.random.permutation(range(num_data))

feats_train = features[index[:num_train]]
Y_train = Y[index[:num_train]]

feats_val = features[index[num_train:]]
Y_val = Y[index[num_train:]]

# We need these later for plotting
X_train = X[index[:num_train]]
X_val = X[index[num_train:]]


# ##################################################################
# Load the test dataset and apply same transformations 
# as we did with the train dataset.
df_test = pd.read_csv(path_test)
df_test_c = df_test.copy(deep=True)
df_test['1'] = np.log10(df_test_c['1'])
df_test['2'] = np.log10(df_test_c['2'])

f = lambda x: -1.0 if x==0 else 1.0
df_test['4'] = df_test_c['4'].map(f)
data_test = df_test.to_numpy()

X_test_ini = data_test[:, 0:4]
Y_test = data_test[:, -1]

# scale data using sklearn StandardScaler
std_slc = StandardScaler(with_mean=False)
std_slc.fit(X_test_ini)
X_test_std = std_slc.transform(X_test_ini)

# normalize data using sklearn StandardScaler
normalizer = Normalizer().fit(X_test_std)  # fit does nothing.
X_test_norm = normalizer.transform(X_test_std)

# convert to a pennylane numpy array
X_test = np.array(X_test_norm, requires_grad=False)

# #########################################################################
# 
def test_accuracy(weights, bias):

    # apply the variational clasifier circuit on test dataset
    # using the learned weights
    predictions_test = [np.sign(variational_classifier(weights, bias, f)) for f in X_test]

    return accuracy(Y_test, predictions_test)


StandardScaler(with_mean=False)

In [66]:
shape = qml.QAOAEmbedding.shape(n_layers=num_layers, n_wires=num_qubits)
weights_init = np.random.random(shape)
bias_init = np.array(0.0, requires_grad=True)


opt = NesterovMomentumOptimizer(0.01) 
# opt = NesterovMomentumOptimizer(0.1) # ok
# opt = NesterovMomentumOptimizer(0.5)
# batch_size = 5
# batch_size = 15
# batch_size = 20
batch_size = 10


# train the variational classifier
weights = weights_init
bias = bias_init
steps = 90 # acc: 0.89
# steps = 5

for it in range(steps):

    # Update the weights by one optimizer step
    batch_index = np.random.randint(0, num_train, (batch_size,))
    feats_train_batch = feats_train[batch_index]
    Y_train_batch = Y_train[batch_index]
    weights, bias, _, _ = opt.step(cost, weights, bias, feats_train_batch, Y_train_batch)

    # Compute predictions on train and validation set
    predictions_train = [np.sign(variational_classifier(weights, bias, f)) for f in feats_train]
    predictions_val = [np.sign(variational_classifier(weights, bias, f)) for f in feats_val]

    # Compute accuracy on train and validation set
    acc_train = accuracy(Y_train, predictions_train)
    acc_val = accuracy(Y_val, predictions_val)

    acc_test = test_accuracy(weights, bias)

    # print(
    #     "Iter: {:5d} | Cost: {:0.7f} | Acc train: {:0.7f} | Acc validation: {:0.7f} "
    #     "".format(it + 1, cost(weights, bias, features, Y), acc_train, acc_val)
    # )

    print(
        "Iter: {:5d} | Cost: {:0.7f} | Acc train: {:0.7f} | Acc validation: {:0.7f} | Acc test: {:0.7f} "
        "".format(it + 1, cost(weights, bias, features, Y), acc_train, acc_val, acc_test)
    )


    if acc_train >= 0.93 and acc_val >= 0.93:
        # early stop
        break

print('bias: ', bias)    
print('weights:\n', weights)
# np.save('/_jupyter/QC/QOSF-challenge-md-2022/task-02/temp-data/variational_classifier/data/mock_train_numpy_wights_02.npy', weights, allow_pickle=True)



Iter:     1 | Cost: 1.8212823 | Acc train: 0.5111111 | Acc validation: 0.5600000 | Acc test: 0.4833333 
Iter:     2 | Cost: 1.0296806 | Acc train: 0.5333333 | Acc validation: 0.5600000 | Acc test: 0.5833333 
Iter:     3 | Cost: 1.1889821 | Acc train: 0.5111111 | Acc validation: 0.4133333 | Acc test: 0.5166667 
Iter:     4 | Cost: 1.1028200 | Acc train: 0.4666667 | Acc validation: 0.4800000 | Acc test: 0.8416667 
Iter:     5 | Cost: 1.3055322 | Acc train: 0.5333333 | Acc validation: 0.5333333 | Acc test: 0.4833333 
Iter:     6 | Cost: 1.0441662 | Acc train: 0.5200000 | Acc validation: 0.5466667 | Acc test: 0.4833333 
Iter:     7 | Cost: 1.7034816 | Acc train: 0.5111111 | Acc validation: 0.5600000 | Acc test: 0.4833333 
Iter:     8 | Cost: 1.4302438 | Acc train: 0.4977778 | Acc validation: 0.6000000 | Acc test: 0.4833333 
Iter:     9 | Cost: 1.6264451 | Acc train: 0.5111111 | Acc validation: 0.5600000 | Acc test: 0.4833333 
Iter:    10 | Cost: 1.1917331 | Acc train: 0.4977778 | Acc valid

KeyboardInterrupt: 

Load the test dataset and apply same transformations as we did with the train dataset.


In [ ]:

acc_test = test_accuracy(weights, bias)
print('Accuracy on test data: {:0.4f}'.format(acc_test))

In [ ]:
# # We can plot the continuous output of the variational classifier for the first two dimensions of the data set.
# plt.figure()
# cm = plt.cm.RdBu

# # make data for decision regions
# xx, yy = np.meshgrid(np.linspace(0.0, 1.5, 300), np.linspace(0.0, 1.5, 300))
# X_grid = [np.array([x, y]) for x, y in zip(xx.flatten(), yy.flatten())]

# pd.DataFrame(xx).shape
# pd.DataFrame(yy).shape
# pd.DataFrame(X_grid).shape

In [ ]:

# # # preprocess grid points like data inputs above
# # padding = 0.3 * np.ones((len(X_grid), 1))
# # X_grid = np.c_[np.c_[X_grid, padding], np.zeros((len(X_grid), 1))]  # pad each input

# # normalization = np.sqrt(np.sum(X_grid ** 2, -1))
# # X_grid = (X_grid.T / normalization).T  # normalize each input

# # features_grid = np.array(
# #     [get_angles(x) for x in X_grid]
# # )  # angles for state preparation are new features

# X_grid = X_norm
# features_grid = X_grid
# predictions_grid = [variational_classifier(weights, bias, f) for f in features_grid]
# # Z = np.reshape(predictions_grid, xx.shape)
# Z = predictions_grid 

# # plot decision regions
# cnt = plt.contourf(
#     xx, yy, Z, levels=np.arange(-1, 1.1, 0.1), cmap=cm, alpha=0.8, extend="both"
# )
# plt.contour(
#     xx, yy, Z, levels=[0.0], colors=("black",), linestyles=("--",), linewidths=(0.8,)
# )
# plt.colorbar(cnt, ticks=[-1, 0, 1])

# # plot data
# plt.scatter(
#     X_train[:, 0][Y_train == 1],
#     X_train[:, 1][Y_train == 1],
#     c="b",
#     marker="o",
#     edgecolors="k",
#     label="class 1 train",
# )
# plt.scatter(
#     X_val[:, 0][Y_val == 1],
#     X_val[:, 1][Y_val == 1],
#     c="b",
#     marker="^",
#     edgecolors="k",
#     label="class 1 validation",
# )
# # plt.scatter(
# #     X_train[:, 0][Y_train == -1],
# #     X_train[:, 1][Y_train == -1],
# #     c="r",
# #     marker="o",
# #     edgecolors="k",
# #     label="class -1 train",
# # )
# # plt.scatter(
# #     X_val[:, 0][Y_val == -1],
# #     X_val[:, 1][Y_val == -1],
# #     c="r",
# #     marker="^",
# #     edgecolors="k",
# #     label="class -1 validation",
# # )

# plt.legend()
# plt.show()